### ISSUE TITLE
How do I use this app?

### ISSUE THREAD

**Issue by Naozumi2k** [patexoid/ZombieLib2#119]
Hi there, I have an issue during the app starting up. I'm using java version 1.8.0_151 on my linux box
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.patex.storage.StorageService required a bean of type 'com.patex.storage.FileStorage' that could not be found.


Action:

Consider defining a bean of type 'com.patex.storage.FileStorage' in your configuration.
```
Full log I've attached here https://gist.github.com/Naozumi2k/ff9b0d6b8280eff9bba3066cf4cfedf1
Please help to figure out. Thanks

**Comment by patexoid** [comment]
It's still in development and there no simple and funny ui yet (will be in far future, may be)

You should create application properties file in work dir and set 
_spring.profiles.active = fileStorage_

other properties are optional(full prop list in /core/src/main/resources/application.properties)

_logging.config = /media/usb/Zlib/logback-spring.xml_

to speed up duplication book search and mark
_duplicateCheck.shingleCoeff=23
duplicateCheck.fastCacheSize=1000
duplicateCheck.storageCacheFolder=./cache/shingle_


If you want telegram (usefull if you want to use this as proxy to external opds servers)
_telegram.bot.token = 
telegram.bot.name = 
telegram.bot.baseurl = http://url:8080_ (required to connect user and telegram chat)

if you want upload lot of book just copy them to folder and they will be uploaded
_bulkUploadDir=./bulkUpload_

After application run you should send post request to create first user _url:8080/user/create_
with body _{"username":"<username>", "password":"password"}_

then register it in your opds client _url:8080/opds_  

you can upload books via _url:8080/index.html_ 
or you can update EXT_LIBRARY table with other opds server config and use this as proxy (can work via tor and i2p proxies )
 for example flibusta via tor installed on the same machine 
_INSERT INTO PUBLIC.EXT_LIBRARY (LOGIN, PASSWORD, URL, NAME, OPDS_PATH, PROXY_TYPE, PROXY_HOST, PROXY_PORT) VALUES (null, null, 'http://flibustahezeous3.onion', 'flibusta Tor', 'opds', 'SOCKS', '127.0.0.1', 9050);_
