### ISSUE TITLE
Как подключиться к внешнему opds?

### ISSUE THREAD

**Issue by alexvelin** [patexoid/ZombieLib2#163]
Здравствуйте. Как подключиться к внешнему каталогу? - Благодаря опубликованному issue я сумел запустить сервис и создать пользователя. Книги загружаются, все работает просто замечательно 👍 Но, к сожалению, дальше возникли сложности, с которыми мне самому как-то не справиться  :( Нужно какой-то POST-запрос отправить?

**Comment by patexoid** [comment]
Хм, как то не замечал что через запрос это сейчас не работает.
Пока единственный возможный способ это сделать запись в базу напрямую в таблицу EXT_LIBRARY
база данный H2, находится в ./bin/h2/db 
jdbc:h2:file:./bin/h2/db;AUTO_SERVER=TRUE
юзер sa пароля нет.
Так же рекомендую создать и привязать к пользователю телеграмм бота так как вся информация о загрузках и возможных дубликатах с внешних opds будет идти через него
создание бота тут https://core.telegram.org/bots
привязка делается с помощью параметров telegram.bot.token, telegram.bot.name и telegram.bot.baseurl  в application.properties

потом надо подключится к этому боту, дать команду /subscribe и клацнуть на ссылку
в случае проблем с ботом можно подебажить com.patex.messaging.TelegramMessenger#response или com.patex.controllers.ZUserController#updateUserConfig

**Comment by alexvelin** [comment]
Спасибо, попробую
